### ISSUE TITLE
install.sh fails

### ISSUE THREAD

**Issue by williamh** [Netflix/dispatch-docker#103]
I am working on installing dispatch so that I can evaluate it for my company.
My `.env` file is identical to the `.env.example` file in the repository
other than the secrets.

Step 25 of the installation process fails as follows.
I'm not sure what I'm missing in the initial configuration, so any help would be
greatly appreciated.

Thanks,

William

```
Step 25/47 : RUN export YARN_CACHE_FOLDER="$(mktemp -d)"     && cd /usr/src/dispatch     && python setup.py bdist_wheel     && rm -r "$YARN_CACHE_FOLDER"     && mv /usr/src/dispatch/dist /dist
 ---> Running in 20a992ece4f8
running bdist_wheel
running build
running build_assets
using node (v12.16.2)


#
# Fatal error in , line 0
# Check failed: reservation_.SetPermissions(protect_start, protect_size, permission).
#
#
#
#FailureMessage Object: 0x7bc8f6e776e0
 1: 0xa70671  [node]
 2: 0x19d8915 V8_Fatal(char const*, ...) [node]
 3: 0xd9197f  [node]
 4: 0xd9469d v8::internal::PagedSpace::SetReadAndExecutable() [node]
 5: 0xcd75b3 v8::internal::Isolate::Init(v8::internal::ReadOnlyDeserializer*, v8::internal::StartupDeserializer*) [node]
 6: 0x10b8dee v8::internal::Snapshot::Initialize(v8::internal::Isolate*) [node]
 7: 0xb9989d v8::Isolate::Initialize(v8::Isolate*, v8::Isolate::CreateParams const&) [node]
 8: 0xa44f81 node::NodeMainInstance::NodeMainInstance(v8::Isolate::CreateParams*, uv_loop_s*, node::MultiIsolatePlatform*, std::vector<std::string, std::allocator<std::string> > const&, std::vector<std::string, std::allocator<std::string> > const&, std::vector<unsigned long, std::allocator<unsigned long> > const*) [node]
 9: 0x9d4e10 node::Start(int, char**) [node]
10: 0x72e20791f09b __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
11: 0x96ec55  [node]
command failed [npm install] via [/usr/src/dispatch/src/dispatch/static/dispatch]
Traceback (most recent call last):
  File "setup.py", line 382, in <module>
    setup(
  File "/usr/local/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/usr/local/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/local/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/local/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 299, in run
    self.run_command('build')
  File "/usr/local/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/local/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 360, in run
    self.run_command("build_assets")
  File "/usr/local/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/local/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 192, in run
    self._setup_js_deps()
  File "setup.py", line 146, in _setup_js_deps
    self._run_npm_command(["install"])
  File "setup.py", line 159, in _run_npm_command
    self._run_command(["npm"] + cmd, env=env)
  File "setup.py", line 153, in _run_command
    return check_output(cmd, cwd=self.work_path, env=env)
  File "/usr/local/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/local/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['npm', 'install']' died with <Signals.SIGILL: 4>.
Removing intermediate container 20a992ece4f8
Service 'core' failed to build : The command '/bin/sh -c export YARN_CACHE_FOLDER="$(mktemp -d)"     && cd /usr/src/dispatch     && python setup.py bdist_wheel     && rm -r "$YARN_CACHE_FOLDER"     && mv /usr/src/dispatch/dist /dist' returned a non-zero code: 1
Cleaning up...
```

**Comment by williamh** [comment]
@dimuit86 wsl isn't an option I can use, so is there anything I can do to help debug this?

**Comment by kevgliss** [comment]
@williamh you are running this on windows though? If you could give us some more info about which host os you're using that might help narrow things down. Unfortunately, I don't have access to a windows environment.

**Comment by kevgliss** [comment]
Which distro? Which version? I'm running the latest docker and ubuntu 20.10 and am unable to reproduce... so I will need more information about your environment.

**Comment by williamh** [comment]
Hi all,

sorry for the noise; the issue was on my side.
The VM I was installing on had the grsecurity patches applied to the kernel.
We re-deployed the vm without that kernel and the install succeeded.

**Comment by kevgliss** [comment]
No worries, glad you were able to figure it out.
