### ISSUE TITLE
Fix Database Upgrade step in install.sh

### ISSUE THREAD

**Issue by TheDahv** [Netflix/dispatch-docker#11]
The installation script runs `docker-compose run --rm dispatch database upgrade` as one of the last steps of setting up Dispatch.

There are a few issues:

- it references a service called "dispatch" which does not exist
- changing the service to a service that has DB access (e.g., "web") produces the configuration error below
- the upgrade command does not appear to recognize the "--no-input" argument

```
 $ docker compose run --rm web database upgrade                                                                                                                            [51/1608]
Creating network "dispatch_default" with the default driver
Creating dispatch_postgres_1 ... done
Traceback (most recent call last):
  File "/usr/local/bin/dispatch", line 8, in <module>
    sys.exit(entrypoint())
  File "/usr/local/lib/python3.8/site-packages/dispatch/cli.py", line 766, in entrypoint
    dispatch_cli()
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/dispatch/cli.py", line 553, in upgrade_database
    alembic_command.upgrade(alembic_cfg, revision, sql=sql, tag=tag)
  File "/usr/local/lib/python3.8/site-packages/alembic/command.py", line 278, in upgrade
    script = ScriptDirectory.from_config(config)
  File "/usr/local/lib/python3.8/site-packages/alembic/script/base.py", line 126, in from_config
    script_location = config.get_main_option("script_location")
  File "/usr/local/lib/python3.8/site-packages/alembic/config.py", line 293, in get_main_option
    return self.get_section_option(self.config_ini_section, name, default)
  File "/usr/local/lib/python3.8/site-packages/alembic/config.py", line 276, in get_section_option
    raise util.CommandError(
alembic.util.exc.CommandError: No config file '/usr/local/lib/python3.8/site-packages/dispatch/alembic.ini' found, or file has no '[alembic]' section

**Comment by TheDahv** [comment]
cf; https://github.com/Netflix/dispatch/issues/59

@daniel-gallagher I'd be curious to see if the inclusion of the Alembic packages and config makes a difference here.

**Comment by daniel-gallagher** [comment]
I believe it might. I think I have a solution and will know if it's successful in a moment once the docker image builds.

**Comment by daniel-gallagher** [comment]
This should now be resolved by Netflix/dispatch/pull/62

**Comment by TheDahv** [comment]
@daniel-gallagher excellent. That got me pretty close. I can boot up the command now, but the migrations themselves fail:

https://github.com/Netflix/dispatch/issues/66

**Comment by TheDahv** [comment]
Alright, I'm good to go now. Leaving behind what it took for me to recover in case anybody comes here in the future:

https://github.com/Netflix/dispatch/issues/66#issuecomment-592773291
