### ISSUE TITLE
Problem with reaccessing the organization after renaming

### ISSUE THREAD

**Issue by olam-slack** [Netflix/dispatch-docker#131]
Hello, I got an error constantly about "Organization not found" in the UI, after renaming the organization and logging out and logging in again.

My user is an owner. I checked the database tables dispatch_core.dispatch_user, .dispatch_user_organization, .organization, the mapping for my user should be fine. 

Thanks for your reply in advance.

**Comment by mvilanova** [comment]
Thanks for the report. What did you rename the org to? Can you share the error in the server logs?

**Comment by olam-slack** [comment]
Hi Marc, I renamed to organization1. Attached below the log.


INFO:     172.24.0.1:60832 - "POST /default/auth/login HTTP/1.1" 422 Unprocessable Entity
ERROR:dispatch.main:1 validation error for OrganizationRead
organization
  Organization not found. (type=value_error.not_found; msg=Organization not found.; organization=default)
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/dispatch/main.py", line 184, in dispatch
    response = await call_next(request)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/base.py", line 44, in call_next
    raise app_exc
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/base.py", line 34, in coro
    await self.app(scope, request.receive, send_stream.send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/base.py", line 63, in __call__
    response = await self.dispatch_func(request, call_next)
  File "/usr/local/lib/python3.9/site-packages/dispatch/main.py", line 172, in dispatch
    raise e from None
  File "/usr/local/lib/python3.9/site-packages/dispatch/main.py", line 168, in dispatch
    response = await call_next(request)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/base.py", line 44, in call_next
    raise app_exc
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/base.py", line 34, in coro
    await self.app(scope, request.receive, send_stream.send)
  File "/usr/local/lib/python3.9/site-packages/sentry_asgi/middleware.py", line 22, in __call__
    raise exc from None
  File "/usr/local/lib/python3.9/site-packages/sentry_asgi/middleware.py", line 19, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/base.py", line 63, in __call__
    response = await self.dispatch_func(request, call_next)
  File "/usr/local/lib/python3.9/site-packages/dispatch/main.py", line 144, in db_session_middleware

**Comment by mvilanova** [comment]
Thanks. I'll see if I can repro it today and get back to you.
