### ISSUE TITLE
basic ./install.sh crashes building container on step 49/49

### ISSUE THREAD

**Issue by elasticdotventures** [Netflix/dispatch-docker#142]
**Describe the bug**

sqlalchemy.exc.InternalError: (psycopg2.errors.DependentObjectsStillExist) cannot drop function organization_search_vector_update() because other objects depend on it
DETAIL:  trigger organization_search_vector_trigger on table organization depends on function organization_search_vector_update()

** Detail **

my org is planning to evaluate netflix/dispatch for application suitability. 
I am tasked with leading this review (so I'm *very* new to this application & architecture)

I did a quick /smoke test/ cloned repo, ran `./install.sh` on fresh ubuntu 22.04 system crashed during build process with an sqlAlchemy issue on step 49/49 .. and I now plan to spend a bit of time diagnosing this (which I will post on this thread)

```
Step 49/49 : LABEL org.opencontainers.image.licenses="https://github.com/netflix/dispatch/blob/${SOURCE_COMMIT:-master}/LICENSE"
 ---> Running in fa7f11fc1dd9
Removing intermediate container fa7f11fc1dd9
 ---> 8a5a6a427fdf
Successfully built 8a5a6a427fdf
Successfully tagged dispatch-local:latest

Docker images pulled and built.
Creating network "dispatch_default" with the default driver
Creating dispatch_postgres_1 ... done

Setting up database...
Do you want to load example data (WARNING: this will remove all existing database data) (y/N)?Initializing the database
Creating dispatch_core_1 ... done
Creating dispatch_web_run ... done

/usr/local/lib/python3.9/site-packages/requests/__init__.py:102: RequestsDependencyWarning: urllib3 (1.26.9) or chardet (5.0.0)/charset_normalizer (2.0.12) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({})/charset_normalizer ({}) doesn't match a supported "
Initializing new database...
Success.
Running standard database migrations...
Creating dispatch_web_run ... done
/usr/local/lib/python3.9/site-packages/requests/__init__.py:102: RequestsDependencyWarning: urllib3 (1.26.9) or chardet (5.0.0)/charset_normalizer (2.0.12) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({})/charset_normalizer ({}) doesn't match a supported "
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.DependentObjectsStillExist: cannot drop function organization_search_vector_update() because other objects depend on it
DETAIL:  trigger organization_search_vector_trigger on table organization depends on function organization_search_vector_update()
HINT:  Use DROP ... CASCADE to drop the dependent objects too.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/dispatch", line 8, in <module>
    sys.exit(entrypoint())
  File "/usr/local/lib/python3.9/site-packages/dispatch/cli.py", line 794, in entrypoint
    dispatch_cli()
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/dispatch/cli.py", line 380, in upgrade_database
    setup_fulltext_search(conn, get_core_tables())
  File "/usr/local/lib/python3.9/site-packages/dispatch/database/manage.py", line 172, in setup_fulltext_search
    sync_trigger(**trigger)
  File "/usr/local/lib/python3.9/site-packages/dispatch/search/fulltext/__init__.py", line 404, in sync_trigger
    conn.execute(str(sql), **sql.params)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1003, in execute
    return self._execute_text(object_, multiparams, params)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1172, in _execute_text
    ret = self._execute_context(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.InternalError: (psycopg2.errors.DependentObjectsStillExist) cannot drop function organization_search_vector_update() because other objects depend on it
DETAIL:  trigger organization_search_vector_trigger on table organization depends on function organization_search_vector_update()
HINT:  Use DROP ... CASCADE to drop the dependent objects too.

[SQL: DROP FUNCTION IF EXISTS dispatch_core.organization_search_vector_update()]
(Background on this error at: http://sqlalche.me/e/13/2j85)
ERROR: 1
Cleaning up...
```

**Comment by elasticdotventures** [comment]
`docker-compose build` does work.

**Comment by mvilanova** [comment]
@elasticdotventures there's a fix for this issue in the dispatch master branch that will be included in the next release. Until then, you can remove `#latest` from this line: https://github.com/Netflix/dispatch-docker/blob/master/docker-compose.yml#L22
