### ISSUE TITLE
cant able to start dispatch

### ISSUE THREAD

**Issue by csetarun2** [Netflix/dispatch-docker#146]
Hi all, 
I have just cloned repo and tried to build , the example data has loaded, when I start the docker-compose its keep on restarting
<img width="938" alt="image" src="https://user-images.githubusercontent.com/21236859/225711551-f9ca8bae-e2f8-4ff0-bbb1-4bfd31810bac.png">

<img width="942" alt="image" src="https://user-images.githubusercontent.com/21236859/225711632-07bcc4f4-c22a-4447-99d9-fb7cd6481f67.png">

here are my logs

`
root@ip-172-31-46-112:/home/ubuntu/dispatch-docker# docker logs 5acab295acc6
Traceback (most recent call last):
  File "/usr/local/bin/dispatch", line 8, in <module>
    sys.exit(entrypoint())
  File "/usr/local/lib/python3.9/site-packages/dispatch/cli.py", line 812, in entrypoint
    dispatch_cli()
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/uvicorn/main.py", line 403, in main
    run(
  File "/usr/local/lib/python3.9/site-packages/uvicorn/main.py", line 568, in run
    server.run()
  File "/usr/local/lib/python3.9/site-packages/uvicorn/server.py", line 59, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/usr/local/lib/python3.9/site-packages/uvicorn/server.py", line 66, in serve
    config.load()
  File "/usr/local/lib/python3.9/site-packages/uvicorn/config.py", line 471, in load
    self.loaded_app = import_from_string(self.app)
  File "/usr/local/lib/python3.9/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/local/lib/python3.9/site-packages/dispatch/main.py", line 22, in <module>
    from .api import api_router
  File "/usr/local/lib/python3.9/site-packages/dispatch/api.py", line 13, in <module>
    from dispatch.case.views import router as case_router
  File "/usr/local/lib/python3.9/site-packages/dispatch/case/views.py", line 31, in <module>
    from .flows import (
  File "/usr/local/lib/python3.9/site-packages/dispatch/case/flows.py", line 16, in <module>
    from dispatch.incident import flows as incident_flows
  File "/usr/local/lib/python3.9/site-packages/dispatch/incident/flows.py", line 56, in <module>
    ) -> tuple[list[Participant | None], list[Participant | None]]:
TypeError: unsupported operand type(s) for |: 'DeclarativeMeta' and 'NoneType'
Traceback (most recent call last):
  File "/usr/local/bin/dispatch", line 8, in <module>
    sys.exit(entrypoint())
  File "/usr/local/lib/python3.9/site-packages/dispatch/cli.py", line 812, in entrypoint
    dispatch_cli()
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/uvicorn/main.py", line 403, in main
    run(
  File "/usr/local/lib/python3.9/site-packages/uvicorn/main.py", line 568, in run
    server.run()
  File "/usr/local/lib/python3.9/site-packages/uvicorn/server.py", line 59, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/usr/local/lib/python3.9/site-packages/uvicorn/server.py", line 66, in serve
    config.load()
  File "/usr/local/lib/python3.9/site-packages/uvicorn/config.py", line 471, in load
    self.loaded_app = import_from_string(self.app)
  File "/usr/local/lib/python3.9/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/local/lib/python3.9/site-packages/dispatch/main.py", line 22, in <module>
    from .api import api_router
  File "/usr/local/lib/python3.9/site-packages/dispatch/api.py", line 13, in <module>
    from dispatch.case.views import router as case_router
  File "/usr/local/lib/python3.9/site-packages/dispatch/case/views.py", line 31, in <module>
    from .flows import (
  File "/usr/local/lib/python3.9/site-packages/dispatch/case/flows.py", line 16, in <module>
    from dispatch.incident import flows as incident_flows
  File "/usr/local/lib/python3.9/site-packages/dispatch/incident/flows.py", line 56, in <module>
    ) -> tuple[list[Participant | None], list[Participant | None]]:
TypeError: unsupported operand type(s) for |: 'DeclarativeMeta' and 'NoneType'
Traceback (most recent call last):
  File "/usr/local/bin/dispatch", line 8, in <module>
    sys.exit(entrypoint())
  File "/usr/local/lib/python3.9/site-packages/dispatch/cli.py", line 812, in entrypoint
    dispatch_cli()
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/uvicorn/main.py", line 403, in main
    run(
  File "/usr/local/lib/python3.9/site-packages/uvicorn/main.py", line 568, in run
    server.run()
  File "/usr/local/lib/python3.9/site-packages/uvicorn/server.py", line 59, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/usr/local/lib/python3.9/site-packages/uvicorn/server.py", line 66, in serve
    config.load()
  File "/usr/local/lib/python3.9/site-packages/uvicorn/config.py", line 471, in load
    self.loaded_app = import_from_string(self.app)
  File "/usr/local/lib/python3.9/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/local/lib/python3.9/site-packages/dispatch/main.py", line 22, in <module>
    from .api import api_router
  File "/usr/local/lib/python3.9/site-packages/dispatch/api.py", line 13, in <module>
    from dispatch.case.views import router as case_router
  File "/usr/local/lib/python3.9/site-packages/dispatch/case/views.py", line 31, in <module>
    from .flows import (
  File "/usr/local/lib/python3.9/site-packages/dispatch/case/flows.py", line 16, in <module>
    from dispatch.incident import flows as incident_flows
  File "/usr/local/lib/python3.9/site-packages/dispatch/incident/flows.py", line 56, in <module>
    ) -> tuple[list[Participant | None], list[Participant | None]]:
TypeError: unsupported operand type(s) for |: 'DeclarativeMeta' and 'NoneType'
Traceback (most recent call last):
  File "/usr/local/bin/dispatch", line 8, in <module>
    sys.exit(entrypoint())
  File "/usr/local/lib/python3.9/site-packages/dispatch/cli.py", line 812, in entrypoint
    dispatch_cli()
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/uvicorn/main.py", line 403, in main
    run(
  File "/usr/local/lib/python3.9/site-packages/uvicorn/main.py", line 568, in run
    server.run()
  File "/usr/local/lib/python3.9/site-packages/uvicorn/server.py", line 59, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/usr/local/lib/python3.9/site-packages/uvicorn/server.py", line 66, in serve
    config.load()
  File "/usr/local/lib/python3.9/site-packages/uvicorn/config.py", line 471, in load
    self.loaded_app = import_from_string(self.app)
  File "/usr/local/lib/python3.9/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/local/lib/python3.9/site-packages/dispatch/main.py", line 22, in <module>
    from .api import api_router
  File "/usr/local/lib/python3.9/site-packages/dispatch/api.py", line 13, in <module>
    from dispatch.case.views import router as case_router
  File "/usr/local/lib/python3.9/site-packages/dispatch/case/views.py", line 31, in <module>
    from .flows import (
  File "/usr/local/lib/python3.9/site-packages/dispatch/case/flows.py", line 16, in <module>
    from dispatch.incident import flows as incident_flows
  File "/usr/local/lib/python3.9/site-packages/dispatch/incident/flows.py", line 56, in <module>
    ) -> tuple[list[Participant | None], list[Participant | None]]:
TypeError: unsupported operand type(s) for |: 'DeclarativeMeta' and 'NoneType'
Traceback (most recent call last):
  File "/usr/local/bin/dispatch", line 8, in <module>
    sys.exit(entrypoint())
  File "/usr/local/lib/python3.9/site-packages/dispatch/cli.py", line 812, in entrypoint
    dispatch_cli()
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/uvicorn/main.py", line 403, in main
    run(
  File "/usr/local/lib/python3.9/site-packages/uvicorn/main.py", line 568, in run
    server.run()
  File "/usr/local/lib/python3.9/site-packages/uvicorn/server.py", line 59, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/usr/local/lib/python3.9/site-packages/uvicorn/server.py", line 66, in serve
    config.load()
  File "/usr/local/lib/python3.9/site-packages/uvicorn/config.py", line 471, in load
    self.loaded_app = import_from_string(self.app)
  File "/usr/local/lib/python3.9/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/local/lib/python3.9/site-packages/dispatch/main.py", line 22, in <module>
    from .api import api_router
  File "/usr/local/lib/python3.9/site-packages/dispatch/api.py", line 13, in <module>
    from dispatch.case.views import router as case_router
  File "/usr/local/lib/python3.9/site-packages/dispatch/case/views.py", line 31, in <module>
    from .flows import (
  File "/usr/local/lib/python3.9/site-packages/dispatch/case/flows.py", line 16, in <module>
    from dispatch.incident import flows as incident_flows
  File "/usr/local/lib/python3.9/site-packages/dispatch/incident/flows.py", line 56, in <module>
    ) -> tuple[list[Participant | None], list[Participant | None]]:
TypeError: unsupported operand type(s) for |: 'DeclarativeMeta' and 'NoneType'
root@ip-172-31-46-112:/home/ubuntu/dispatch-docker# docker ps
`

**Comment by wssheldon** [comment]
Please try again with the latest changes merged in https://github.com/Netflix/dispatch/pull/3120
