### ISSUE TITLE
ERROR: No such service: dispatch. Unable to complete installation

### ISSUE THREAD

**Issue by rascasoft** [Netflix/dispatch-docker#17]
The installation script fails while starting the database stuff, after building everything with success and launching this command:
```
rasca@catastrofe [~/dispatch-docker]> docker-compose run --rm dispatch database upgrade --noinput
ERROR: No such service: dispatch
```
I wasn't able to find relations between this failure and what is [described here](https://github.com/Netflix/dispatch-docker/issues/11), even though the failure is the same.

I think a user would expect after launching ./install.sh to have everything in place, instead it seems that some bits and pieces are missing and need to be made by hand, and I'm still trying to identify the whole of them.

**Comment by nnegi79** [comment]
We are facing same issue.

**Comment by eglenfield** [comment]
@rascasoft @nnegi79 if you remove `dispatch` from the `docker-compose run` command it will get you a step further, in the Dockerfile for the dispatch app the entrypoint is set to `dispatch`, so it will being the dispatch app in that context therefore you don't need to call it again.

**Comment by chandu-s-d** [comment]
Tried by removing the **dispatch** from the **docker-compose run** command. this time getting the **ERROR: No such service: database**

**Comment by eglenfield** [comment]
> Tried by removing the **dispatch** from the **docker-compose run** command. this time getting the **ERROR: No such service: database**

Ah right sorry these are the changes I made, I should have said to point to the web container (think we're all struggling to get it running first time so I've been combining multiple fixes):

```
if [ $CI ]; then
docker-compose run web --help
  docker-compose run web database upgrade --no-input
else
  docker-compose run web --help
  docker-compose run web database upgrade
fi

```

**Comment by chandu-s-d** [comment]
Again tried today with the changes above you suggested, But, still unable to complete the installation. Getting below error. 
_**+ docker-compose run --rm dispatch postgres upgrade
Creating network "dispatch_default" with the default driver
Traceback (most recent call last):
  File "/usr/local/bin/dispatch", line 5, in <module>
    from dispatch.cli import entrypoint
  File "/usr/local/lib/python3.8/site-packages/dispatch/cli.py", line 12, in <module>
    from dispatch import __version__, config
  File "/usr/local/lib/python3.8/site-packages/dispatch/config.py", line 43, in <module>
    DISPATCH_HELP_EMAIL = config("DISPATCH_HELP_EMAIL")
  File "/usr/local/lib/python3.8/site-packages/starlette/config.py", line 62, in __call__
    return self.get(key, cast, default)
  File "/usr/local/lib/python3.8/site-packages/starlette/config.py", line 75, in get
    raise KeyError(f"Config '{key}' is missing, and has no default.")
KeyError: "Config 'DISPATCH_HELP_EMAIL' is missing, and has no default."
++ cleanup
++ '[' 0 -eq 1 ']'
++ echo 'Cleaning up...'
Cleaning up...
++ docker-compose stop
++ DID_CLEAN_UP=1**_
This might help you to fix the issue. Please suggest us once you fix the issue.

**Comment by eglenfield** [comment]
@chandu-s-d PR up with changes I made to get dispatch running successful, **please note** you need admin access/service accounts for all plugins otherwise the application falls over: https://github.com/Netflix/dispatch-docker/pull/20

**Comment by chandu-s-d** [comment]
Hi, 

I've cloned brand new repo and then tried installation. But still failing with below errors.

**_+ docker-compose run web database upgrade
Starting dispatch_postgres_1 ... done
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2276, in _wrap_pool_connect
    return fn()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 303, in unique_connection
    return _ConnectionFairy._checkout(self)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 773, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 492, in checkout
    rec = pool._do_get()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 238, in _do_get
    return self._create_connection()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 308, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 437, in __init__
    self.__connect(first_connect_check=True)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 652, in __connect
    connection = pool._invoke_creator(self)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 489, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/usr/local/lib/python3.8/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  database "dispatch" does not exist


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/dispatch", line 8, in <module>
    sys.exit(entrypoint())
  File "/usr/local/lib/python3.8/site-packages/dispatch/cli.py", line 793, in entrypoint
    dispatch_cli()
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/dispatch/cli.py", line 580, in upgrade_database
    alembic_command.upgrade(alembic_cfg, revision, sql=sql, tag=tag)
  File "/usr/local/lib/python3.8/site-packages/alembic/command.py", line 298, in upgrade
    script.run_env()
  File "/usr/local/lib/python3.8/site-packages/alembic/script/base.py", line 489, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/usr/local/lib/python3.8/site-packages/alembic/util/pyfiles.py", line 98, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/local/lib/python3.8/site-packages/alembic/util/compat.py", line 184, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.8/site-packages/dispatch/alembic/env.py", line 84, in <module>
    run_migrations_online()
  File "/usr/local/lib/python3.8/site-packages/dispatch/alembic/env.py", line 74, in run_migrations_online
    with connectable.connect() as connection:
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2209, in connect
    return self._connection_cls(self, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 103, in __init__
    else engine.raw_connection()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2306, in raw_connection
    return self._wrap_pool_connect(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2279, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1547, in _handle_dbapi_exception_noconnection
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2276, in _wrap_pool_connect
    return fn()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 303, in unique_connection
    return _ConnectionFairy._checkout(self)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 773, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 492, in checkout
    rec = pool._do_get()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 238, in _do_get
    return self._create_connection()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 308, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 437, in __init__
    self.__connect(first_connect_check=True)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 652, in __connect
    connection = pool._invoke_creator(self)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 489, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/usr/local/lib/python3.8/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) FATAL:  database "dispatch" does not exist

(Background on this error at: http://sqlalche.me/e/e3q8)
++ cleanup
++ '[' 0 -eq 1 ']'
++ echo 'Cleaning up...'
Cleaning up...
++ docker-compose stop
++ DID_CLEAN_UP=1_**

And I am using default .env.example file only. I just added values to **DISPATCH_DOMAIN** and **DISPATCH_HELP_EMAIL** And my compose file pointing to develop branch. 

Please suggest us to resolve the issue and to complete the installation.

**Comment by juanvasquezreyes** [comment]
I ran the following and worked for me

Make sure you have the .env with the credentials for the DB

docker-compose run web database drop \
  && docker-compose run web database init \
  && docker-compose run web database sync-triggers \
  && docker-compose run web database upgrade

**Comment by chandu-s-d** [comment]
Most of my config issues related to **.env** file has been resolved but still facing the connectivity issues with the below error. unable to complete installation. 
Error: **sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name ""postgres"" to address: Name or service not known**

**Comment by eglenfield** [comment]
Make sure you've pulled the latest changes would definitely be my first port of call. https://github.com/Netflix/dispatch-docker/blob/4436d93babd125c71a5d041be0f1bc2b85939ff3/install.sh#L86 - ^ this line should spin up the postgres db for the step below to run successfully: https://github.com/Netflix/dispatch-docker/blob/4436d93babd125c71a5d041be0f1bc2b85939ff3/install.sh#L116. If you have also built the images you can comment out these three lines for a faster execution: https://github.com/Netflix/dispatch-docker/blob/4436d93babd125c71a5d041be0f1bc2b85939ff3/install.sh#L80-L82

**Comment by chandu-s-d** [comment]
Yes i have pulled the latest changes, And i am trying as per suggestions provided in this thread. And also I've tried by executing the above mentioned commands manually once i built the images. But no luck. still facing the same issue. 

Error: sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name ""postgres"" to address: Name or service not known

**Note**: I am using **ubuntu** machine.

**Comment by eglenfield** [comment]
@chandu-s-d Is the docker network being setup correctly? The output I have when it successfully runs is (the swarm reference can be ignored): 

```
Successfully built 3aff1af1cd5e
Successfully tagged dispatch-local:latest

Docker images built.
WARNING: The Docker Engine you're using is running in swarm mode.

Compose does not use swarm mode to deploy services to multiple nodes in a swarm. All containers will be scheduled on the current node.

To deploy your application across the swarm, use `docker stack deploy`.

Creating network "dispatch-docker_default" with the default driver
Creating dispatch-docker_postgres_1 ... done

Setting up database...
Starting dispatch-docker_postgres_1 ... done
Usage: dispatch [OPTIONS] COMMAND [ARGS]...

  Command-line interface to Dispatch.

Options:
  --version  Show the version and exit.
  --help     Show this message and exit.

Commands:
  contact    All commands for contact manipulation.
  database   Container for all dispatch database commands.
  incident   All commands for incident manipulation.
  plugins    All commands for plugin manipulation.
  scheduler  Container for all dispatch scheduler commands.
  server     Container for all dispatch server commands.
  term       All commands for term manipulation.
Starting dispatch-docker_postgres_1 ... done
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
Success.
Cleaning up...

----------------
You're all done! Run the following command to get Dispatch running:

  docker-compose up -d
```

**Comment by chandu-s-d** [comment]
we have observed one thing is without database upgrade, if we run the command as **docker-compose run web** we can see that containers are running, But schedular container is throwing error related to JIRA. We are checking now by configuring JIRA details in .env. But, By running the only **docker-compose run web** without database upgrade will the application work? 

And also what are all the required configurations we have to maintain in .env? as we now we just using below ones.

**DISPATCH_DOMAIN="xxxxxxxxxxx"
DATABASE_HOSTNAME="postgres"
DATABASE_CREDENTIALS="postgres:dispatch"
POSTGRES_PASSWORD="dispatch"

DISPATCH_HELP_EMAIL="xxxxxxx.com"
DISPATCH_HELP_SLACK_CHANNEL="https://chandu-xxxxxx"
DISPATCH_PKCE_AUTH_ENABLED="False"
VUE_APP_DISPATCH_PKCE_AUTH="False"
JWKS_URL="None"**

**Comment by karl-johan-grahn** [comment]
I also wonder what the required configurations are, @eglenfield can you please provide your full env file here since you have it working?

**Comment by chandu-s-d** [comment]
I've built the images with latest changes, And I ran **docker-compose up -d postgres** and then 
**docker-compose run web**. By running those two commands I can see that containers are running as below
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                    NAMES
c66d54f41499        dispatch-local      "dispatch server sta…"   16 hours ago        Up 16 hours         0.0.0.0:80->8000/tcp     dispatch_web_1
761dd95f99a5        dispatch-local      "dispatch server sta…"   16 hours ago        Up 16 hours         8000/tcp                 dispatch_dispatch-scheduler_1
1f9cf5006407        postgres:9.6        "docker-entrypoint.s…"   16 hours ago        Up 16 hours         0.0.0.0:5432->5432/tcp   dispatch_postgres_1

But we are unable to get the page  in browser. It's showing blank. Below are my compose file and .env file

version: "3.4"
x-restart-policy: &restart_policy
  restart: unless-stopped
x-dispatch-defaults: &dispatch_defaults
  <<: *restart_policy
  build:
    context: https://github.com/Netflix/dispatch.git#develop
    dockerfile: docker/Dockerfile
  image: dispatch-local
  depends_on:
    - postgres
  env_file:
    - .env
services:
  postgres:
    <<: *restart_policy
    image: "postgres:9.6"
    ports:
      - "5432:5432"
    volumes:
      - "dispatch-postgres:/var/lib/postgresql/data"
    env_file: ./.env
    networks:
      - dispatch
  web:
    networks:
      - dispatch
    <<: *dispatch_defaults
    ports:
      - "80:8000"
    links:
        - "postgres:database"
  dispatch-scheduler:
    <<: *dispatch_defaults
volumes:
  dispatch-postgres:
    external: true
networks:
  dispatch:
    driver: bridge

below is my .env file
===============
DISPATCH_DOMAIN="xxxxxxxxxxx"
DATABASE_HOSTNAME="postgres"
DATABASE_CREDENTIALS="postgres:dispatch"
POSTGRES_PASSWORD="dispatch"

DISPATCH_HELP_EMAIL="xxxxxxx.com"
DISPATCH_HELP_SLACK_CHANNEL="https://chandu-xxxxxx"
DISPATCH_PKCE_AUTH_ENABLED="False"
VUE_APP_DISPATCH_PKCE_AUTH="False"
JWKS_URL="None"
# Incident configuration
INCIDENT_NOTIFICATION_CONVERSATIONS=""
INCIDENT_NOTIFICATION_DISTRIBUTION_LISTS=""
INCIDENT_STORAGE_ARCHIVAL_FOLDER_ID=""
INCIDENT_STORAGE_DRIVE_ID_SLUG=""
INCIDENT_STORAGE_INCIDENT_REVIEW_FILE_ID=""
INCIDENT_DOCUMENT_INVESTIGATION_SHEET_ID=""
INCIDENT_FAQ_DOCUMENT_ID=""

# Plugin configuration

# Slack
SLACK_APP_USER_SLUG=""
SLACK_API_BOT_TOKEN=""
SLACK_SIGNING_SECRET=""
SLACK_WORKSPACE_NAME=""

# Google
GOOGLE_SERVICE_ACCOUNT_PROJECT_ID=""
GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY_ID=""
GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY=""
GOOGLE_SERVICE_ACCOUNT_CLIENT_EMAIL=""
GOOGLE_SERVICE_ACCOUNT_CLIENT_ID=""
GOOGLE_SERVICE_ACCOUNT_DELEGATED_ACCOUNT=""
GOOGLE_DEVELOPER_KEY=""
GOOGLE_DOMAIN=""

# Jira
JIRA_BROWSER_URL="https://delhivery.atlassian.net"
JIRA_PASSWORD=""
JIRA_USERNAME=""
JIRA_API_URL=""
JIRA_PROJECT_KEY=""
JIRA_ISSUE_TYPE_ID=""

# PagerDuty
PAGERDUTY_API_KEY=""
PAGERDUTY_API_FROM_EMAIL=""


And also If i check for the docker logs for running schedular container, below are the errors.

docker logs 102fd185b1db
No metric providers specified metrics will not be sent.
ERROR:    Unable to import dispatch.plugins.dispatch_google.docs.plugin.GoogleDocsDocumentPlugin. Reason: Could not deserialize key data.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/dispatch/common/managers.py", line 61, in all
    results.append(cls())
  File "/usr/local/lib/python3.8/site-packages/dispatch/plugins/dispatch_google/docs/plugin.py", line 107, in __init__
    self.client = get_service("docs", "v1", scopes).documents()
  File "/usr/local/lib/python3.8/site-packages/dispatch/plugins/dispatch_google/common.py", line 39, in get_service
    credentials = service_account.Credentials.from_service_account_file(
  File "/usr/local/lib/python3.8/site-packages/google/oauth2/service_account.py", line 217, in from_service_account_file
    info, signer = _service_account_info.from_filename(
  File "/usr/local/lib/python3.8/site-packages/google/auth/_service_account_info.py", line 74, in from_filename
    return data, from_dict(data, require=require)
  File "/usr/local/lib/python3.8/site-packages/google/auth/_service_account_info.py", line 55, in from_dict
    signer = crypt.RSASigner.from_service_account_info(data)
  File "/usr/local/lib/python3.8/site-packages/google/auth/crypt/base.py", line 113, in from_service_account_info
    return cls.from_string(
  File "/usr/local/lib/python3.8/site-packages/google/auth/crypt/_cryptography_rsa.py", line 146, in from_string
    private_key = serialization.load_pem_private_key(
  File "/usr/local/lib/python3.8/site-packages/cryptography/hazmat/primitives/serialization/base.py", line 16, in load_pem_private_key
    return backend.load_pem_private_key(data, password)
  File "/usr/local/lib/python3.8/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1085, in load_pem_private_key
    return self._load_key(
  File "/usr/local/lib/python3.8/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1315, in _load_key
    self._handle_key_loading_error()
  File "/usr/local/lib/python3.8/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1373, in _handle_key_loading_error
    raise ValueError("Could not deserialize key data.")
ValueError: Could not deserialize key data.
ERROR:    Unable to import dispatch.plugins.dispatch_google.drive.plugin.GoogleDriveStoragePlugin. Reason: Could not deserialize key data.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/dispatch/common/managers.py", line 61, in all
    results.append(cls())
  File "/usr/local/lib/python3.8/site-packages/dispatch/plugins/dispatch_google/drive/plugin.py", line 48, in __init__
    self.client = get_service("drive", "v3", scopes)
  File "/usr/local/lib/python3.8/site-packages/dispatch/plugins/dispatch_google/common.py", line 39, in get_service
    credentials = service_account.Credentials.from_service_account_file(
  File "/usr/local/lib/python3.8/site-packages/google/oauth2/service_account.py", line 217, in from_service_account_file
    info, signer = _service_account_info.from_filename(
  File "/usr/local/lib/python3.8/site-packages/google/auth/_service_account_info.py", line 74, in from_filename
    return data, from_dict(data, require=require)
  File "/usr/local/lib/python3.8/site-packages/google/auth/_service_account_info.py", line 55, in from_dict
    signer = crypt.RSASigner.from_service_account_info(data)
  File "/usr/local/lib/python3.8/site-packages/google/auth/crypt/base.py", line 113, in from_service_account_info
    return cls.from_string(
  File "/usr/local/lib/python3.8/site-packages/google/auth/crypt/_cryptography_rsa.py", line 146, in from_string
    private_key = serialization.load_pem_private_key(
  File "/usr/local/lib/python3.8/site-packages/cryptography/hazmat/primitives/serialization/base.py", line 16, in load_pem_private_key
    return backend.load_pem_private_key(data, password)
  File "/usr/local/lib/python3.8/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1085, in load_pem_private_key
    return self._load_key(
  File "/usr/local/lib/python3.8/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1315, in _load_key
    self._handle_key_loading_error()
  File "/usr/local/lib/python3.8/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1373, in _handle_key_loading_error
    raise ValueError("Could not deserialize key data.")
ValueError: Could not deserialize key data.
ERROR:    Unable to import dispatch.plugins.dispatch_google.drive.plugin.GoogleDriveTaskPlugin. Reason: Could not deserialize key data.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/dispatch/common/managers.py", line 61, in all
    results.append(cls())
  File "/usr/local/lib/python3.8/site-packages/dispatch/plugins/dispatch_google/drive/plugin.py", line 133, in __init__
    self.client = get_service("drive", "v3", scopes)
  File "/usr/local/lib/python3.8/site-packages/dispatch/plugins/dispatch_google/common.py", line 39, in get_service
    credentials = service_account.Credentials.from_service_account_file(
  File "/usr/local/lib/python3.8/site-packages/google/oauth2/service_account.py", line 217, in from_service_account_file
    info, signer = _service_account_info.from_filename(
  File "/usr/local/lib/python3.8/site-packages/google/auth/_service_account_info.py", line 74, in from_filename
    return data, from_dict(data, require=require)
  File "/usr/local/lib/python3.8/site-packages/google/auth/_service_account_info.py", line 55, in from_dict
    signer = crypt.RSASigner.from_service_account_info(data)
  File "/usr/local/lib/python3.8/site-packages/google/auth/crypt/base.py", line 113, in from_service_account_info
    return cls.from_string(
  File "/usr/local/lib/python3.8/site-packages/google/auth/crypt/_cryptography_rsa.py", line 146, in from_string
    private_key = serialization.load_pem_private_key(
  File "/usr/local/lib/python3.8/site-packages/cryptography/hazmat/primitives/serialization/base.py", line 16, in load_pem_private_key
    return backend.load_pem_private_key(data, password)
  File "/usr/local/lib/python3.8/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1085, in load_pem_private_key
    return self._load_key(
  File "/usr/local/lib/python3.8/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1315, in _load_key
    self._handle_key_loading_error()
  File "/usr/local/lib/python3.8/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1373, in _handle_key_loading_error
    raise ValueError("Could not deserialize key data.")
ValueError: Could not deserialize key data.
ERROR:    Unable to import dispatch.plugins.dispatch_google.gmail.plugin.GoogleGmailConversationPlugin. Reason: Could not deserialize key data.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/dispatch/common/managers.py", line 61, in all
    results.append(cls())
  File "/usr/local/lib/python3.8/site-packages/dispatch/plugins/dispatch_google/gmail/plugin.py", line 135, in __init__
    self.client = get_service("gmail", "v1", scopes)
  File "/usr/local/lib/python3.8/site-packages/dispatch/plugins/dispatch_google/common.py", line 39, in get_service
    credentials = service_account.Credentials.from_service_account_file(
  File "/usr/local/lib/python3.8/site-packages/google/oauth2/service_account.py", line 217, in from_service_account_file
    info, signer = _service_account_info.from_filename(
  File "/usr/local/lib/python3.8/site-packages/google/auth/_service_account_info.py", line 74, in from_filename
    return data, from_dict(data, require=require)
  File "/usr/local/lib/python3.8/site-packages/google/auth/_service_account_info.py", line 55, in from_dict
    signer = crypt.RSASigner.from_service_account_info(data)
  File "/usr/local/lib/python3.8/site-packages/google/auth/crypt/base.py", line 113, in from_service_account_info
    return cls.from_string(
  File "/usr/local/lib/python3.8/site-packages/google/auth/crypt/_cryptography_rsa.py", line 146, in from_string
    private_key = serialization.load_pem_private_key(
  File "/usr/local/lib/python3.8/site-packages/cryptography/hazmat/primitives/serialization/base.py", line 16, in load_pem_private_key
    return backend.load_pem_private_key(data, password)
  File "/usr/local/lib/python3.8/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1085, in load_pem_private_key
    return self._load_key(
  File "/usr/local/lib/python3.8/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1315, in _load_key
    self._handle_key_loading_error()
  File "/usr/local/lib/python3.8/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1373, in _handle_key_loading_error
    raise ValueError("Could not deserialize key data.")
ValueError: Could not deserialize key data.
ERROR:    Unable to import dispatch.plugins.dispatch_google.groups.plugin.GoogleGroupParticipantGroupPlugin. Reason: Could not deserialize key data.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/dispatch/common/managers.py", line 61, in all
    results.append(cls())
  File "/usr/local/lib/python3.8/site-packages/dispatch/plugins/dispatch_google/groups/plugin.py", line 130, in __init__
    self.client = get_service("admin", "directory_v1", scopes)
  File "/usr/local/lib/python3.8/site-packages/dispatch/plugins/dispatch_google/common.py", line 39, in get_service
    credentials = service_account.Credentials.from_service_account_file(
  File "/usr/local/lib/python3.8/site-packages/google/oauth2/service_account.py", line 217, in from_service_account_file
    info, signer = _service_account_info.from_filename(
  File "/usr/local/lib/python3.8/site-packages/google/auth/_service_account_info.py", line 74, in from_filename
    return data, from_dict(data, require=require)
  File "/usr/local/lib/python3.8/site-packages/google/auth/_service_account_info.py", line 55, in from_dict
    signer = crypt.RSASigner.from_service_account_info(data)
  File "/usr/local/lib/python3.8/site-packages/google/auth/crypt/base.py", line 113, in from_service_account_info
    return cls.from_string(
  File "/usr/local/lib/python3.8/site-packages/google/auth/crypt/_cryptography_rsa.py", line 146, in from_string
    private_key = serialization.load_pem_private_key(
  File "/usr/local/lib/python3.8/site-packages/cryptography/hazmat/primitives/serialization/base.py", line 16, in load_pem_private_key
    return backend.load_pem_private_key(data, password)
  File "/usr/local/lib/python3.8/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1085, in load_pem_private_key
    return self._load_key(
  File "/usr/local/lib/python3.8/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1315, in _load_key
    self._handle_key_loading_error()
  File "/usr/local/lib/python3.8/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1373, in _handle_key_loading_error
    raise ValueError("Could not deserialize key data.")
ValueError: Could not deserialize key data.
ERROR:    Unable to import dispatch.plugins.dispatch_jira.plugin.JiraTicketPlugin. Reason: Invalid URL '""/rest/api/2/serverInfo': No schema supplied. Perhaps you meant http://""/rest/api/2/serverInfo?
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/dispatch/common/managers.py", line 61, in all
    results.append(cls())
  File "/usr/local/lib/python3.8/site-packages/dispatch/plugins/dispatch_jira/plugin.py", line 216, in __init__
    self.client = JIRA(str(JIRA_API_URL), basic_auth=(JIRA_USERNAME, str(JIRA_PASSWORD)))
  File "/usr/local/lib/python3.8/site-packages/jira/client.py", line 472, in __init__
    si = self.server_info()
  File "/usr/local/lib/python3.8/site-packages/jira/client.py", line 2133, in server_info
    j = self._get_json('serverInfo')
  File "/usr/local/lib/python3.8/site-packages/jira/client.py", line 2549, in _get_json
    r = self._session.get(url, params=params)
  File "/usr/local/lib/python3.8/site-packages/jira/resilientsession.py", line 151, in get
    return self.__verb('GET', url, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/jira/resilientsession.py", line 125, in __verb
    response = method(url, timeout=self.timeout, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 516, in request
    prep = self.prepare_request(req)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 449, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 314, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 388, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '""/rest/api/2/serverInfo': No schema supplied. Perhaps you meant http://""/rest/api/2/serverInfo?
INFO:     Started server process [1]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)


Could you please help with the required configurations and where we are missing the things to resolve above errors.

**Comment by eglenfield** [comment]
@chandu-s-d @karl-johan-grahn All the plugin env fields must be filled in, you can't run the app without also having the plugin details (which should all have admin rights to the relevant plugins), as describes on this issue on the app repo: https://github.com/Netflix/dispatch/issues/55. The base I used before adding the relevant creds for my org was the .env.example file in the main dir, also not as well the majority of fields do not require quotation marks.

**Comment by kevgliss** [comment]
Yes, today all the plugin fields need to be set for the app to start. For folks that don't want to go through that setup process; we will be working on some generic plugins that don't require at configuration (you won't be able to do much, but the app will start).

**Comment by chandu-s-d** [comment]
Hi,

As per the suggestions, we almost filled our config file with all the configurations, except below.

**JWKS_URL="None"
# Incident configuration
#Comma separated list of conversations (e.g. Slack channels) to be notified of new incidents.
INCIDENT_NOTIFICATION_CONVERSATIONS=""
#Comma separated list of email addresses to be notified of new incidents.
INCIDENT_NOTIFICATION_DISTRIBUTION_LISTS="xxxxxxx@xxxx.com"
#Controls the folder where to archive incident information.
INCIDENT_STORAGE_ARCHIVAL_FOLDER_ID=""
INCIDENT_STORAGE_DRIVE_ID_SLUG=""
INCIDENT_STORAGE_INCIDENT_REVIEW_FILE_ID=""
INCIDENT_DOCUMENT_INVESTIGATION_SHEET_ID=""
#Controls which document id to use as the FAQ.
INCIDENT_FAQ_DOCUMENT_ID=""**

We are not sure, what are values we have to use for the above configurations. Could you please suggest what are the values we need to use?

**Comment by kevgliss** [comment]
@chandu-s-d for the values you mentioned take a look at: https://hawkins.gitbook.io/dispatch/configuration/app#incident-resource-configuration

Essentially what they are still vary depending on which plugins you use, if you plan to use Google Drive/Docs (the default) these IDs are the google resource IDs you want to use. 

For example, Dispatch can use a google document as a template for incident review, if you pass that fileid to `INCIDENT_STORAGE_INCIDENT_REVIEW_FILE_ID` it will create a copy of that document for you and an incident is marked as stable.
