### ISSUE TITLE
relation "application" does not exist

### ISSUE THREAD

**Issue by karl-johan-grahn** [Netflix/dispatch-docker#35]
Building with this `.env` file:
```
# For configuration details, see: https://hawkins.gitbook.io/dispatch/configuration/app

DISPATCH_UI_URL=localhost

COMPOSE_PROJECT_NAME=dispatch

# General

DATABASE_HOSTNAME=postgres
DATABASE_CREDENTIALS=postgres:dispatch
DATABASE_NAME=dispatch
DATABASE_PORT=5432
POSTGRES_PASSWORD=dispatch
POSTGRES_DB=dispatch
POSTGRES_USER=postgres

DISPATCH_HELP_EMAIL=""
DISPATCH_HELP_SLACK_CHANNEL=""

DISPATCH_PKCE_AUTH_ENABLED="False"
VUE_APP_DISPATCH_PKCE_AUTH="False"
JWKS_URL="None"
DISPATCH_AUTHENTICATION_PROVIDER=""

# Incident configuration
INCIDENT_CONVERSATION_COMMANDS_REFERENCE_DOCUMENT_ID=""
INCIDENT_NOTIFICATION_CONVERSATIONS=""
INCIDENT_NOTIFICATION_DISTRIBUTION_LISTS=""
INCIDENT_STORAGE_ARCHIVAL_FOLDER_ID=""
INCIDENT_STORAGE_DRIVE_ID_SLUG=""
INCIDENT_STORAGE_INCIDENT_REVIEW_FILE_ID=""
INCIDENT_DOCUMENT_INVESTIGATION_SHEET_ID=""
INCIDENT_FAQ_DOCUMENT_ID=""

# Plugin configuration

# Slack
SLACK_APP_USER_SLUG=""
SLACK_API_BOT_TOKEN=""
SLACK_SIGNING_SECRET=""
SLACK_WORKSPACE_NAME=""

# Google
GOOGLE_SERVICE_ACCOUNT_PROJECT_ID=""
GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY_ID=""
GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY=""
GOOGLE_SERVICE_ACCOUNT_CLIENT_EMAIL=""
GOOGLE_SERVICE_ACCOUNT_CLIENT_ID=""
GOOGLE_SERVICE_ACCOUNT_DELEGATED_ACCOUNT=""
GOOGLE_DEVELOPER_KEY=""
GOOGLE_DOMAIN=""

# Jira
JIRA_BROWSER_URL=""
JIRA_PASSWORD=""
JIRA_USERNAME=""
JIRA_API_URL=""
JIRA_PROJECT_KEY=""
JIRA_ISSUE_TYPE_ID=""

# PagerDuty
PAGERDUTY_API_KEY=""
PAGERDUTY_API_FROM_EMAIL=""
```
Getting:
```
Setting up database...
Starting dispatch_postgres_1 ... done
Usage: dispatch [OPTIONS] COMMAND [ARGS]...

  Command-line interface to Dispatch.

Options:
  --version  Show the version and exit.
  --help     Show this message and exit.

Commands:
  contact    All commands for contact manipulation.
  database   Container for all dispatch database commands.
  incident   All commands for incident manipulation.
  plugins    All commands for plugin manipulation.
  scheduler  Container for all dispatch scheduler commands.
  server     Container for all dispatch server commands.
  term       All commands for term manipulation.
Starting dispatch_postgres_1 ... done
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> e75e103693f2, Initial migration
INFO  [alembic.runtime.migration] Running upgrade e75e103693f2 -> d0501fc6be89, empty message
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1247, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 588, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedTable: relation "application" does not exist


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/dispatch", line 8, in <module>
    sys.exit(entrypoint())
  File "/usr/local/lib/python3.8/site-packages/dispatch/cli.py", line 835, in entrypoint
    dispatch_cli()
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/dispatch/cli.py", line 612, in upgrade_database
    alembic_command.upgrade(alembic_cfg, revision, sql=sql, tag=tag)
  File "/usr/local/lib/python3.8/site-packages/alembic/command.py", line 298, in upgrade
    script.run_env()
  File "/usr/local/lib/python3.8/site-packages/alembic/script/base.py", line 489, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/usr/local/lib/python3.8/site-packages/alembic/util/pyfiles.py", line 98, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/local/lib/python3.8/site-packages/alembic/util/compat.py", line 184, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.8/site-packages/dispatch/alembic/env.py", line 84, in <module>
    run_migrations_online()
  File "/usr/local/lib/python3.8/site-packages/dispatch/alembic/env.py", line 78, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/usr/local/lib/python3.8/site-packages/alembic/runtime/environment.py", line 846, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/usr/local/lib/python3.8/site-packages/alembic/runtime/migration.py", line 520, in run_migrations
    step.migration_fn(**kw)
  File "/usr/local/lib/python3.8/site-packages/dispatch/alembic/versions/d0501fc6be89_.py", line 21, in upgrade
    op.add_column("application", sa.Column("created_at", sa.DateTime(), nullable=True))
  File "<string>", line 8, in add_column
  File "<string>", line 3, in add_column
  File "/usr/local/lib/python3.8/site-packages/alembic/operations/ops.py", line 1929, in add_column
    return operations.invoke(op)
  File "/usr/local/lib/python3.8/site-packages/alembic/operations/base.py", line 374, in invoke
    return fn(self, operation)
  File "/usr/local/lib/python3.8/site-packages/alembic/operations/toimpl.py", line 132, in add_column
    operations.impl.add_column(table_name, column, schema=schema, **kw)
  File "/usr/local/lib/python3.8/site-packages/alembic/ddl/impl.py", line 237, in add_column
    self._exec(base.AddColumn(table_name, column, schema=schema))
  File "/usr/local/lib/python3.8/site-packages/alembic/ddl/impl.py", line 140, in _exec
    return conn.execute(construct, *multiparams, **params)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 984, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/ddl.py", line 72, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1041, in _execute_ddl
    ret = self._execute_context(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1287, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1481, in _handle_dbapi_exception
    util.raise_(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1247, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 588, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation "application" does not exist

[SQL: ALTER TABLE application ADD COLUMN created_at TIMESTAMP WITHOUT TIME ZONE]
(Background on this error at: http://sqlalche.me/e/f405)
Cleaning up...
```

**Comment by karl-johan-grahn** [comment]
Seems to be https://github.com/Netflix/dispatch/issues/120

**Comment by karl-johan-grahn** [comment]
If I comment out `docker-compose run web database upgrade --no-input` from the install script the install finishes, but no UI accessible.

**Comment by karl-johan-grahn** [comment]
Related to https://github.com/Netflix/dispatch-docker/issues/32 too

**Comment by karl-johan-grahn** [comment]
```
docker logs dispatch_web_1
No metric providers specified metrics will not be sent.
Failed to load plugin zoom_conference. Reason: "Config 'ZOOM_API_USER_ID' is missing, and has no default."
WARNING:  Unable to import fbprophet, some metrics will not be usable.
WARNING:  Failed to load plugin zoom_conference. Reason: "Config 'ZOOM_API_USER_ID' is missing, and has no default."
INFO:     Started server process [1]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
```
No response from `http://0.0.0.0:8000`

**Comment by B3lak0r** [comment]
> ```
> docker logs dispatch_web_1
> No metric providers specified metrics will not be sent.
> Failed to load plugin zoom_conference. Reason: "Config 'ZOOM_API_USER_ID' is missing, and has no default."
> WARNING:  Unable to import fbprophet, some metrics will not be usable.
> WARNING:  Failed to load plugin zoom_conference. Reason: "Config 'ZOOM_API_USER_ID' is missing, and has no default."
> INFO:     Started server process [1]
> INFO:     Waiting for application startup.
> INFO:     Application startup complete.
> INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
> ```
> 
> No response from `http://0.0.0.0:8000`

FYI

At least you'll be able to ge into the UI:

https://github.com/Netflix/dispatch-docker/issues/26#issuecomment-604349500

https://github.com/Netflix/dispatch-docker/issues/32#issuecomment-604447519

Remember:

![image](https://user-images.githubusercontent.com/54198281/78021011-58094c80-734a-11ea-8eb9-cd1329c3c427.png)



So:
JWKS_URL=                                                                                                               DISPATCH_PKCE_AUTH_ENABLED=
VUE_APP_DISPATCH_PKCE_AUTH=
DISPATCH_AUTHENTICATION_PROVIDER=

**Comment by karl-johan-grahn** [comment]
Got it up finally
