### ISSUE TITLE
Unable to import dispatch.plugins.dispatch_google.docs.plugin.GoogleDocsDocumentPlugin

### ISSUE THREAD

**Issue by bdooling** [Netflix/dispatch-docker#38]
Hi all,

I've been slowly making progress on getting Dispatch up and running through Docker, but now I'm stumped (and haven't found any related issues or solutions)

Here's the current error:
```
$ docker-compose up
Recreating dispatch-docker_postgres_1 ... done
Recreating dispatch-docker_dispatch-scheduler_1 ... done
Recreating dispatch-docker_web_1                ... done
Attaching to dispatch-docker_postgres_1, dispatch-docker_web_1, dispatch-docker_dispatch-scheduler_1
postgres_1            |
postgres_1            | PostgreSQL Database directory appears to contain a database; Skipping initialization
postgres_1            |
postgres_1            | LOG:  database system was shut down at 2020-04-03 21:02:11 UTC
postgres_1            | LOG:  MultiXact member wraparound protections are now enabled
postgres_1            | LOG:  database system is ready to accept connections
postgres_1            | LOG:  autovacuum launcher started
web_1                 | No metric providers specified metrics will not be sent.
dispatch-scheduler_1  | No metric providers specified metrics will not be sent.
web_1                 | ERROR:    Unable to import dispatch.plugins.dispatch_google.docs.plugin.GoogleDocsDocumentPlugin. Reason: Could not deserialize key data.
web_1                 | Traceback (most recent call last):
web_1                 |   File "/usr/local/lib/python3.8/site-packages/dispatch/common/managers.py", line 61, in all
web_1                 |     results.append(cls())
web_1                 |   File "/usr/local/lib/python3.8/site-packages/dispatch/plugins/dispatch_google/docs/plugin.py", line 107, in __init__
web_1                 |     self.client = get_service("docs", "v1", scopes).documents()
web_1                 |   File "/usr/local/lib/python3.8/site-packages/dispatch/plugins/dispatch_google/common.py", line 39, in get_service
web_1                 |     credentials = service_account.Credentials.from_service_account_file(
web_1                 |   File "/usr/local/lib/python3.8/site-packages/google/oauth2/service_account.py", line 217, in from_service_account_file
web_1                 |     info, signer = _service_account_info.from_filename(
web_1                 |   File "/usr/local/lib/python3.8/site-packages/google/auth/_service_account_info.py", line 74, in from_filename
web_1                 |     return data, from_dict(data, require=require)
web_1                 |   File "/usr/local/lib/python3.8/site-packages/google/auth/_service_account_info.py", line 55, in from_dict
web_1                 |     signer = crypt.RSASigner.from_service_account_info(data)
web_1                 |   File "/usr/local/lib/python3.8/site-packages/google/auth/crypt/base.py", line 113, in from_service_account_info
web_1                 |     return cls.from_string(
web_1                 |   File "/usr/local/lib/python3.8/site-packages/google/auth/crypt/_cryptography_rsa.py", line 146, in from_string
web_1                 |     private_key = serialization.load_pem_private_key(
web_1                 |   File "/usr/local/lib/python3.8/site-packages/cryptography/hazmat/primitives/serialization/base.py", line 16, in load_pem_private_key
web_1                 |     return backend.load_pem_private_key(data, password)
web_1                 |   File "/usr/local/lib/python3.8/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1085, in load_pem_private_key
web_1                 |     return self._load_key(
web_1                 |   File "/usr/local/lib/python3.8/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1315, in _load_key
web_1                 |     self._handle_key_loading_error()
web_1                 |   File "/usr/local/lib/python3.8/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1373, in _handle_key_loading_error
web_1                 |     raise ValueError("Could not deserialize key data.")
web_1                 | ValueError: Could not deserialize key data.
... <TRIMMED>
```

The web service is responsive, as shown by these logs:

```
web_1                 | INFO:     10.0.2.209:35528 - "GET / HTTP/1.1" 200 OK
web_1                 | INFO:     10.0.2.209:35528 - "GET /static/css/chunk-vendors.c5f0af00.css HTTP/1.1" 200 OK
web_1                 | INFO:     10.0.2.209:35530 - "GET /static/css/app.5f23df13.css HTTP/1.1" 200 OK
web_1                 | INFO:     10.0.2.209:35532 - "GET /static/js/chunk-vendors.afdb7475.js HTTP/1.1" 200 OK
web_1                 | INFO:     10.0.2.209:35536 - "GET /static/js/app.bb6e4494.js HTTP/1.1" 200 OK
web_1                 | INFO:     10.0.2.209:35532 - "GET /img/icons/apple-touch-icon-152x152.png HTTP/1.1" 200 OK
web_1                 | INFO:     10.0.2.209:35536 - "GET /img/icons/favicon-32x32.png HTTP/1.1" 200 OK
```

... but the UI never loads in the browser.

I entered a document ID (located between `https://docs.google.com/document/d/` and `edit` in a Google Doc URL) from the associated Google Drive account in the `INCIDENT_DOCUMENT_INVESTIGATION_SHEET_ID` field, to no effect.

I'd greatly appreciate any ideas / pointers!

**Comment by tomarv2** [comment]
@bdooling you are ahead of me with setup.. wanted to see if you have any idea on these two value, I am putting both as same and tried using API_URL and it works. 

```
JIRA_BROWSER_URL=https://xyz.atlassian.net
JIRA_API_URL=JIRA_API_URL=https://xyz.atlassian.net
```

```
InvalidSchema("No connection adapters were found for {!r}".format(url))
web_1        | requests.exceptions.InvalidSchema: No connection adapters were found for 'JIRA_API_URL=https://xyz.atlassian.net/rest/api/2/serverInfo'
web_1        | 
```

**Comment by mvilanova** [comment]
@bdooling did you configure the G Suite [plugin](https://hawkins.gitbook.io/dispatch/configuration/plugins/configuring-g-suite)?

**Comment by kevgliss** [comment]
@tomarv2 you have: 

`JIRA_API_URL=JIRA_API_URL=https://xyz.atlassian.net`

it should be:
`JIRA_API_URL=https://xyz.atlassian.net`

**Comment by tomarv2** [comment]
@kevgliss it worked
