### ISSUE TITLE
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) fe_sendauth: no password supplied

### ISSUE THREAD

**Issue by kwent** [Netflix/dispatch-docker#50]
Just by running `./install.sh`. I'm on OSX.

```
Setting up database...
Starting dispatch_postgres_1 ... done
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2285, in _wrap_pool_connect
    return fn()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 363, in connect
    return _ConnectionFairy._checkout(self)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 773, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 492, in checkout
    rec = pool._do_get()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 139, in _do_get
    self._dec_overflow()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 136, in _do_get
    return self._create_connection()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 308, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 437, in __init__
    self.__connect(first_connect_check=True)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 657, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 652, in __connect
    connection = pool._invoke_creator(self)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 490, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/usr/local/lib/python3.8/site-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: fe_sendauth: no password supplied
```

.env file

```bash
# For configuration details, see: https://hawkins.gitbook.io/dispatch/configuration/app

# General
COMPOSE_PROJECT_NAME=dispatch
DISPATCH_HELP_EMAIL=help@example.com
DISPATCH_HELP_SLACK_CHANNEL=#general
DISPATCH_UI_URL=https://example.com
SECRET_KEY="iO-S?G0np0=_oA.H7terCFEBI;B^Hnx6(oi3Z\KxWkl0b/5r(\"

# Database
DATABASE_CREDENTIALS=creds
DATABASE_HOSTNAME=postgres
DATABASE_NAME=dispatch
DATABASE_PORT=5432
POSTGRES_DB=dispatch
POSTGRES_PASSWORD=dispatch
POSTGRES_USER=dispatch

# Authentication
DISPATCH_AUTHENTICATION_PROVIDER_PKCE_JWKS=""

# Frontend
VUE_APP_DISPATCH_AUTHENTICATION_PROVIDER_PKCE_OPEN_ID_CONNECT_URL=""
VUE_APP_DISPATCH_AUTHENTICATION_PROVIDER_PKCE_CLIENT_ID=""

# Cost
ANNUAL_COST_EMPLOYEE=50000
BUSINESS_HOURS_YEAR=2080

# Incident configuration
INCIDENT_CONVERSATION_COMMANDS_REFERENCE_DOCUMENT_ID="INCIDENT_CONVERSATION_COMMANDS_REFERENCE_DOCUMENT_ID"
INCIDENT_DAILY_SUMMARY_ONCALL_SERVICE_ID=None
INCIDENT_DOCUMENT_INVESTIGATION_SHEET_ID=""
INCIDENT_DOCUMENT_INVESTIGATION_SHEET_ID="INCIDENT_DOCUMENT_INVESTIGATION_SHEET_ID"
INCIDENT_FAQ_DOCUMENT_ID=""
INCIDENT_FAQ_DOCUMENT_ID="INCIDENT_FAQ_DOCUMENT_ID"
INCIDENT_NOTIFICATION_CONVERSATIONS=""
INCIDENT_NOTIFICATION_CONVERSATIONS=""
INCIDENT_NOTIFICATION_DISTRIBUTION_LISTS=""
INCIDENT_NOTIFICATION_DISTRIBUTION_LISTS=""
INCIDENT_RESOURCE_CONVERSATION_COMMANDS_REFERENCE_DOCUMENT="google-docs-conversation-commands-reference-document"
INCIDENT_RESOURCE_FAQ_DOCUMENT="google-docs-faq-document"
INCIDENT_RESOURCE_INCIDENT_REVIEW_DOCUMENT="google-docs-incident-review-document"
INCIDENT_RESOURCE_INCIDENT_TASK="google-docs-incident-task"
INCIDENT_RESOURCE_INVESTIGATION_DOCUMENT="google-docs-investigation-document"
INCIDENT_RESOURCE_INVESTIGATION_SHEET="google-docs-investigation-sheet"
INCIDENT_RESOURCE_NOTIFICATIONS_GROUP="google-group-participant-notifications-group"
INCIDENT_RESOURCE_TACTICAL_GROUP="google-group-participant-tactical-group"
INCIDENT_STORAGE_ARCHIVAL_FOLDER_ID=""
INCIDENT_STORAGE_ARCHIVAL_FOLDER_ID=INCIDENT_STORAGE_ARCHIVAL_FOLDER_ID
INCIDENT_STORAGE_DRIVE_ID_SLUG=""
INCIDENT_STORAGE_INCIDENT_REVIEW_FILE_ID=""
INCIDENT_STORAGE_INCIDENT_REVIEW_FILE_ID=INCIDENT_STORAGE_INCIDENT_REVIEW_FILE_ID

# Plugin configuration
INCIDENT_PLUGIN_CONTACT_SLUG="slack-contact"
INCIDENT_PLUGIN_CONVERSATION_SLUG="slack-conversation"
INCIDENT_PLUGIN_DOCUMENT_RESOLVER_SLUG="dispatch-document-resolver"
INCIDENT_PLUGIN_DOCUMENT_SLUG="google-docs-document"
INCIDENT_PLUGIN_EMAIL_SLUG="google-gmail-conversation"
INCIDENT_PLUGIN_GROUP_SLUG="group-participant-group"
INCIDENT_PLUGIN_PARTICIPANT_SLUG="dispatch-participants"
INCIDENT_PLUGIN_STORAGE_SLUG="google-drive-storage"
INCIDENT_PLUGIN_TASK_SLUG="google-drive-task"
INCIDENT_PLUGIN_TICKET_SLUG="jira-ticket"

# Slack
SLACK_APP_USER_SLUG=""
SLACK_API_BOT_TOKEN=""
SLACK_SIGNING_SECRET=""
SLACK_WORKSPACE_NAME=""

# Google
GOOGLE_DEVELOPER_KEY=key
GOOGLE_DOMAIN=site.com
GOOGLE_SERVICE_ACCOUNT_CLIENT_EMAIL=info@example.com
GOOGLE_SERVICE_ACCOUNT_CLIENT_ID=id
GOOGLE_SERVICE_ACCOUNT_DELEGATED_ACCOUNT=account
GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY=key
GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY_ID=id
GOOGLE_SERVICE_ACCOUNT_PROJECT_ID=id

# Jira
JIRA_BROWSER_URL=""
JIRA_API_URL=""
JIRA_PROJECT_KEY=""
JIRA_ISSUE_TYPE_ID=""
JIRA_USERNAME=""
JIRA_PASSWORD=""

# PagerDuty
PAGERDUTY_API_KEY=""
PAGERDUTY_API_FROM_EMAIL=""
```

**Comment by mvilanova** [comment]
https://hawkins.gitbook.io/dispatch/configuration/app#database_credentials-secret-true

**Comment by kwent** [comment]
Thank you.

Maybe we could change:

```
# Database
DATABASE_CREDENTIALS=creds
```

to 

```
# Database
DATABASE_CREDENTIALS=dispatch:dispatch
```

so it's ready to go.

**Comment by mvilanova** [comment]
https://github.com/Netflix/dispatch-docker/blob/master/.env.example#L13
