### ISSUE TITLE
KeyError: "Config 'INCIDENT_STORAGE_FOLDER_ID' is missing, and has no default."

### ISSUE THREAD

**Issue by svenmueller** [Netflix/dispatch-docker#67]
After cloning the repo and running `./install.sh`, the setup fails with the following error:

```
...
Starting dispatch_postgres_1 ... done
No JWT secret specified, this is required if you are using basic authentication.
No JWT secret specified, this is required if you are using basic authentication.
Traceback (most recent call last):
  File "/usr/local/bin/dispatch", line 5, in <module>
    from dispatch.cli import entrypoint
  File "/usr/local/lib/python3.8/site-packages/dispatch/cli.py", line 12, in <module>
    from dispatch import __version__, config
  File "/usr/local/lib/python3.8/site-packages/dispatch/config.py", line 161, in <module>
    INCIDENT_STORAGE_FOLDER_ID = config("INCIDENT_STORAGE_FOLDER_ID")
  File "/usr/local/lib/python3.8/site-packages/starlette/config.py", line 62, in __call__
    return self.get(key, cast, default)
  File "/usr/local/lib/python3.8/site-packages/starlette/config.py", line 75, in get
    raise KeyError(f"Config '{key}' is missing, and has no default.")
KeyError: "Config 'INCIDENT_STORAGE_FOLDER_ID' is missing, and has no default."
Cleaning up...
```

**Comment by mvilanova** [comment]
@svenmueller you need to add env var `INCIDENT_STORAGE_FOLDER_ID` to the `.env` file (see https://hawkins.gitbook.io/dispatch/configuration/app#incident_storage_folder_id). We will update the example `.env` file.

**Comment by kevgliss** [comment]
Hmm, it does exist in the example .env here:
https://github.com/Netflix/dispatch-docker/blob/master/.env.example#L42

**Comment by mvilanova** [comment]
@svenmueller were you able to resolve the issue?

**Comment by mvilanova** [comment]
@svenmueller I'm going to close this issue. Feel free to re-open if you're still experiencing it and are able to provide more information.
