### ISSUE TITLE
Running in macOS - dispatch not found

### ISSUE THREAD

**Issue by SurajNerati** [Netflix/dispatch-docker#68]
After running install.sh on my mac laptop, the src/dispatch folder is not generating. And as I some errors with apt-get(in mac apt-get wont work) in the logs. And the setup just ended up like below - 

```Traceback (most recent call last):
  File "/usr/local/bin/dispatch", line 5, in <module>
    from dispatch.cli import entrypoint
  File "/usr/local/lib/python3.8/site-packages/dispatch/cli.py", line 14, in <module>
    from .main import *  # noqa
  File "/usr/local/lib/python3.8/site-packages/dispatch/main.py", line 28, in <module>
    configure_logging()
  File "/usr/local/lib/python3.8/site-packages/dispatch/logging.py", line 11, in configure_logging
    logging.basicConfig(level=LOG_LEVEL)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1994, in basicConfig
    root.setLevel(level)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1409, in setLevel
    self.level = _checkLevel(level)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 194, in _checkLevel
    raise ValueError("Unknown level: %r" % level)
ValueError: Unknown level: '"warning"'
```

**Comment by SurajNerati** [comment]
When I ran docker-compose up -d - 
```ansible|snerati-ltm:dispatch-docker snerati$ docker-compose up -d
Starting dispatch_postgres_1 ... done
Creating dispatch_scheduler_1 ... done
Creating dispatch_web_1       ... done
ansible|snerati-ltm:dispatch-docker snerati$ docker ps
CONTAINER ID        IMAGE                      COMMAND                  CREATED             STATUS              PORTS                    NAMES
cac73e4ca384        dispatch-local-scheduler   "dispatch scheduler …"   3 seconds ago       Up 2 seconds        8000/tcp                 dispatch_scheduler_1
64662b15e0d6        dispatch-local-web         "dispatch server sta…"   3 seconds ago       Up 2 seconds        0.0.0.0:8000->8000/tcp   dispatch_web_1
3ad273ae54d4        postgres                   "docker-entrypoint.s…"   37 minutes ago      Up 2 seconds        0.0.0.0:5432->5432/tcp   dispatch_postgres_1```

In the browser, while saving a report in http://0.0.0.0:8000/incidents/report, I see api errors. 

_POST http://0.0.0.0:8000/api/v1/incidents/ 500 (Internal Server Error)_

**Comment by mvilanova** [comment]
@SurajNerati can you share the contents of your `.env` file? Please redact any sensitive information.
